// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4BYtUUjAP5Fucoqeq3sflKtcEI4vkEcs',
    appId: '1:350265331123:web:c4ec1f259da7f45b0ccfc6',
    messagingSenderId: '350265331123',
    projectId: 'librefit-dev-reels',
    authDomain: 'librefit-dev-reels.firebaseapp.com',
    storageBucket: 'librefit-dev-reels.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5NKJU1yUuTFVo2-jKZOWUI77NeX0iIsA',
    appId: '1:350265331123:android:6e3effca9a3388860ccfc6',
    messagingSenderId: '350265331123',
    projectId: 'librefit-dev-reels',
    storageBucket: 'librefit-dev-reels.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs2FP0FV0Rzve4pPuOaltqFVanzKpTAlA',
    appId: '1:350265331123:ios:a55ef474b05f684d0ccfc6',
    messagingSenderId: '350265331123',
    projectId: 'librefit-dev-reels',
    storageBucket: 'librefit-dev-reels.appspot.com',
    iosClientId: '350265331123-hia1041rr2nruv70hgd7ghue32unb2ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestFlutterUiTemplates',
  );
}
